"""init

Revision ID: 7609396af6da
Revises: 52f68d935fbc
Create Date: 2023-12-23 01:38:56.212182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String
from sqlalchemy.dialects.postgresql import insert
from services.web.settings import CATEGORY_LIST

# revision identifiers, used by Alembic.
revision = '7609396af6da'
down_revision = '52f68d935fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    categories_table = table(
        "category",
        column("category_id", Integer),
        column("category_name", String),
    )

    for category_id, category in enumerate(CATEGORY_LIST, 1):
        insert_stmt = insert(categories_table).values({"category_id": op.inline_literal(category_id),
                                                       "category_name": op.inline_literal(category["category_name"])})
        do_nothing_stmt = insert_stmt.on_conflict_do_nothing(index_elements=["category_id"])
        op.execute(do_nothing_stmt)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
