"""init

Revision ID: 8e0792a7d844
Revises: b92fe8a51809
Create Date: 2023-05-21 17:35:36.277455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0792a7d844'
down_revision = 'b92fe8a51809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_category_article_id_fkey', 'article_category', type_='foreignkey')
    op.drop_constraint('article_category_category_id_fkey', 'article_category', type_='foreignkey')
    op.create_foreign_key(None, 'article_category', 'article', ['article_id'], ['article_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'article_category', 'category', ['category_id'], ['category_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_category', type_='foreignkey')
    op.drop_constraint(None, 'article_category', type_='foreignkey')
    op.create_foreign_key('article_category_category_id_fkey', 'article_category', 'category', ['category_id'], ['category_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('article_category_article_id_fkey', 'article_category', 'article', ['article_id'], ['article_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
