"""set article_date nullable

Revision ID: 95e95da4ef24
Revises: 8e0792a7d844
Create Date: 2023-12-01 19:58:28.497846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e95da4ef24'
down_revision = '8e0792a7d844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'article_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'article_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
